use 50_days_sql_challenge;

--1) Total Revenue : find total business revenue

select
      sum(payment_amount) as total_revenue

    from clean_payments; 

--2) Revenue by date : find daily revenue

SELECT
      payment_date,

      sum(payment_amount) as total_revenue

    from clean_payments

    group by payment_date

    order by payment_date;

--3) Revenue by month : find monthly revenue trend

SELECT
      month(payment_date) as month,

      monthname(payment_date) as monthname,

      sum(payment_amount) as total_revenue

    from clean_payments

    group by month,monthname
    
    order by month ;


--4) Revenue by product : find revenue generated by each product

SELECT
      p.product_id,
      
      p.product_name,

      sum(p.price*od.quantity) as total_revenue

    from clean_products p

    join clean_order_details Od
    on p.product_id=od.product_id

    group by p.product_id,p.product_name;  

--5) Revenue by customer : find customer_wise revenue

SELECT
      c.customer_id,
      
      c.customer_name,

      sum(p.payment_amount) as total_revenue

    from clean_customers c

    join clean_orders O
    on c.customer_id=o.customer_id


    join clean_payments p
    on o.order_id=p.order_id

    group by c.customer_id,c.customer_name

    ORDER BY total_revenue desc;

--6) Revenue by category : find category-wise revenue

SELECT
      p.category,

      sum(od.quantity*p.price) as total_revenue

from clean_products p
join clean_order_details od

on p.product_id=od.product_id

group by p.category

order by tota_revenue desc;  

--7) High revenue days : find days generating high revenue

SELECT
      payment_date,

      sum(payment_amount) as total_revenue

    from clean_payments

    group by payment_date

    order by total_revenue desc;



 





