use 50_days_sql_challenge;

--1) Top selling products : find products sold in highest quantity --

select 
       p.product_id,
       p.product_name,
       sum(od.quantity) as total_sold

from clean_products p

join clean_order_details od
on p.product_id=od.product_id

group by p.product_id,p.product_name

order by total_sold desc;


--2) least selling products : find least selling products


select 
       p.product_id,
       p.product_name,
       sum(od.quantity) as total_sold

from clean_products p

join clean_order_details od
on p.product_id=od.product_id

group by p.product_id,p.product_name

order by total_sold ;


--3)Revenue per product : find revenue generated by each product


select p.product_id,
       p.product_name,
       sum(od.quantity*p.price) as total_revenue

from clean_products p

join clean_order_details Od
on p.product_id = od.product_id

group by p.product_id,p.product_name;


--4) categories wise sales : find total sales for each category 

select
       p.category,
       sum(p.price*od.quantity) as total_revenue

from clean_products p

join clean_order_details od
on p.product_id=od.product_id

group by p.category;

--5)Most expensive product sold : find highest priced product that was sold

SELECT
      distinct p.product_id,

      p.product_name,

      p.price

from clean_products p

join clean_order_details Od
on p.product_id=od.product_id

order by p.price desc
limit 1;


--6) Find average price per category : find average product price category-wise


SELECT
       category,
       
       avg(price) as avg_price

from clean_products

group by category

order by avg_price desc;




